version: "3"
name: home_server
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  gitea_act:
    container_name: gitea_act
    restart: unless-stopped
    image: rynomarree/self-hosted-deployment:latest
    environment:
      GITEA_RUNNER_REGISTRATION_TOKEN: "${RUNNER_TOKEN}"
    volumes:
      - ./gitea_act/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ${REPO_DIR}:/repo