name: Server Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /repo
    steps:
      - name: Set git remote if not already set
        run: git remote -v | grep -w gitea || git remote add gitea "./gitea/git/repositories/${GITHUB_REPOSITORY,,}.git"

      - name: Checkout repo
        run: git pull gitea main

      - name: Set environment variables
        run: echo "${{ secrets.SERVER_ENV_PROD }}" > .env

      - name: Deploy
        run: docker compose up -d --remove-orphans

      - name: Restart services if files changed
        run: /restart_if_files_changed.sh "homeassistant" "dashy" "zigbee2mqtt"